name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Build Docker image
      run: docker build -t playwright-tests .

    - name: Print current directory
      run: pwd

    - name: List files in the container
      run: ls -l

    - name: Run Playwright tests and generate report
      run: |
        npx playwright test --reporter=html --output=playwright-report
        ls -l ./playwright-report

    - name: Deploy Playwright Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./playwright-report  
        publish_branch: gh-pages
        keep_files: true
