name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Build Docker image
      run: docker build -t playwright-tests .

    - name: Run tests in Docker
      run: docker run --rm playwright-tests
      
    - name: Generate Playwright HTML report
  run: |
    docker run --rm playwright-tests npx playwright test --reporter=html --output=playwright-report

    - name: Deploy Playwright Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report  
        publish_branch: gh-pages
        keep_files: true

    - name: Verify gh-pages content
      run: |
        git fetch origin
        git checkout gh-pages
        ls -la
