name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Build Docker image
      run: 
        docker build -t playwright-tests .

    - name: Run tests in Docker and generate Playwright HTML report
      run: |
        # Создание отчетов в папке 'playwright-report'
        docker run --rm playwright-tests npx playwright test --reporter=html --output=playwright-report

    - name: Deploy Playwright Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./playwright-report 
        publish_branch: gh-pages  

    - name: Show git status before deployment
      run: |
        git status
        git log -n 1

    - name: Show files after deployment
      run: |
        git ls-tree -r gh-pages --name-only
